# Generated by Django 5.1.4 on 2024-12-30 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, help_text='Unique identifier for the WeChat user.', max_length=128)),
                ('unionid', models.CharField(blank=True, help_text='Unique identifier for the WeChat Open Platform user.', max_length=128)),
                ('nickname', models.CharField(blank=True, help_text='WeChat user nickname.', max_length=30)),
                ('avatar_url', models.URLField(blank=True, help_text="URL link to the WeChat user's avatar.")),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text="User's gender.", max_length=10)),
                ('country', models.CharField(blank=True, help_text='Country of the user.', max_length=30)),
                ('province', models.CharField(blank=True, help_text='Province of the user.', max_length=30)),
                ('city', models.CharField(blank=True, help_text='City of the user.', max_length=30)),
                ('language', models.CharField(blank=True, help_text='Language preference of the user.', max_length=30)),
                ('bio', models.TextField(blank=True, help_text='Personal biography.', max_length=500)),
                ('location', models.CharField(blank=True, help_text='Geographical location.', max_length=30)),
                ('birth_date', models.DateField(blank=True, help_text='Date of birth.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
