# Generated by Django 5.1.4 on 2025-11-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='openid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unionid',
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_completed',
            field=models.BooleanField(default=False, help_text='Indicates whether user has completed the registration process (set password, virtual email, scene selection).'),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_token',
            field=models.CharField(blank=True, db_index=True, help_text='Temporary token for email registration verification. Expires after REGISTRATION_TOKEN_EXPIRY_HOURS.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_token_expires',
            field=models.DateTimeField(blank=True, help_text='Expiration datetime for registration_token.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone for displaying dates and times. Common values: 'UTC', 'Asia/Shanghai', 'America/New_York', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text="URL link to the user's avatar."),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Personal biography or description.', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-US', 'English'), ('zh-CN', '简体中文'), ('es', 'Español')], default='en-US', help_text='Specifies the language used by AI when generating summaries, titles, and metadata. This is a global setting shared across all applications.', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, help_text='User nickname.', max_length=30),
        ),
    ]
