# Generated by Django 5.1.4 on 2025-12-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_birth_date_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-US', 'English'), ('zh-CN', '简体中文'), ('es', 'Español'), ('ja-JP', '日本語'), ('ko-KR', '한국어')], default='zh-CN', help_text='Specifies the language used by AI when generating summaries, titles, and metadata. This is a global setting shared across all applications.', max_length=10),
        ),
    ]
