# Generated by Django 5.1.4 on 2026-02-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_update_profile_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                default="Asia/Shanghai",
                help_text="User's timezone for displaying dates and times. Common values: 'UTC', 'Asia/Shanghai', 'America/New_York', etc.",
                max_length=50,
            ),
        ),
    ]
