# Generated by Django 5.1.4 on 2026-02-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcore_notifier', '0005_notificationchannel_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationrecord',
            new_name='notifier_no_provide_fcf309_idx',
            old_name='notifier_no_provider_source_4a7c80_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrecord',
            new_name='notifier_no_status_4cb7c9_idx',
            old_name='notifier_no_status_created_2b0f3a_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrecord',
            new_name='notifier_no_created_0d1d41_idx',
            old_name='notifier_no_created_at_1f8d9e_idx',
        ),
        migrations.RenameIndex(
            model_name='notifierconfig',
            new_name='agentcore_n_scope_6db98a_idx',
            old_name='agentcore_notifier_config_scope_key_idx',
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Webhook: provider_type, url, message_prefix, sign_secret, merge_*, silence_window_minutes; email: smtp_*, from_email, etc.'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If True, this channel is used for sending when none specified.'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Send priority: smaller = higher; same value uses created_at.'),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='channel_link',
            field=models.ForeignKey(blank=True, db_column='channel_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='agentcore_notifier.notificationchannel'),
        ),
    ]
