# Generated by Django 5.1.4 on 2026-02-20 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentcore_metering", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "Global"), ("user", "User")],
                        db_index=True,
                        help_text="global = site default; user = per-user",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="openai",
                        help_text="openai | azure_openai | gemini",
                        max_length=50,
                    ),
                ),
                (
                    "openai_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="OPENAI_CONFIG: api_key, model, base_url.",
                    ),
                ),
                (
                    "azure_openai_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AZURE_OPENAI_CONFIG: api_key, api_base.",
                    ),
                ),
                (
                    "gemini_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="GEMINI_CONFIG: api_key, model, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM Config",
                "verbose_name_plural": "LLM Configs",
                "db_table": "agentcore_metering_llm_config",
            },
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for global config; set for user override",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="llmconfig",
            constraint=models.UniqueConstraint(
                fields=("scope", "user"),
                name="agentcore_metering_llm_config_scope_user_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "global")),
                fields=("scope",),
                name="agentcore_metering_llm_config_single_global",
            ),
        ),
    ]
