# Generated by Django 5.1.4 on 2026-02-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentcore_metering", "0003_llm_config_single_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusage",
            name="cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=None,
                help_text="Estimated cost in USD (e.g. LiteLLM reference)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
