# Generated by Django 5.1.4 on 2026-02-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentcore_metering", "0008_llmconfig_add_uuid"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="llmusage",
            new_name="llm_tracker_user_id_5800dd_idx",
            old_name="llm_track_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="llmusage",
            new_name="llm_tracker_model_534b34_idx",
            old_name="llm_track_model_created_idx",
        ),
        migrations.RenameIndex(
            model_name="llmusage",
            new_name="llm_tracker_total_t_f8ac69_idx",
            old_name="llm_track_tokens_created_idx",
        ),
        migrations.RenameIndex(
            model_name="llmusage",
            new_name="llm_tracker_success_3cd796_idx",
            old_name="llm_track_success_created_idx",
        ),
        migrations.RenameIndex(
            model_name="llmusage",
            new_name="llm_tracker_created_60798a_idx",
            old_name="llm_track_created_at_idx",
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-specific config (api_key, model, api_base, etc.).",
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="model_type",
            field=models.CharField(
                db_index=True,
                default="llm",
                help_text="LiteLLM call type: llm (completion), embedding, image_generation.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="order",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                help_text="Order for picking config (first active by order).",
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="scope",
            field=models.CharField(
                choices=[("global", "Global"), ("user", "User")],
                db_index=True,
                help_text="global = site default; user = per-user override",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="llmusage",
            name="cost_currency",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="USD",
                help_text="ISO 4217 currency code (e.g. USD, CNY). LiteLLM uses USD.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="llmusage",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Context and source info: node_name, source_type, source_task_id, source_path, etc. Flat structure for flexible querying.",
            ),
        ),
    ]
