# Generated by Django 5.1.4 on 2026-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcore_metering', '0011_llmconfig_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmconfig',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'LLM Config', 'verbose_name_plural': 'LLM Configs'},
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='If true, this global config is used when model_uuid is not set. Only one global LLM config should be default; setting one clears others. Ignored for user-scope configs.'),
        ),
    ]
