# Generated by Django 5.1.4 on 2026-02-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentcore_metering", "0013_llmusage_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmusage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="When the record was saved after call completed (t_end).",
            ),
        ),
        migrations.AlterField(
            model_name="llmusage",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the LLM request started (t_start). Used for E2E latency.",
                null=True,
            ),
        ),
    ]
