# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentcore_metering", "0014_alter_llmusage_created_at_alter_llmusage_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusage",
            name="is_streaming",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the call was made in streaming mode",
            ),
        ),
        migrations.AddField(
            model_name="llmusage",
            name="first_chunk_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text=(
                    "When the first content chunk arrived (streaming only). "
                    "Used for TTFT = first_chunk_at - started_at."
                ),
                null=True,
            ),
        ),
    ]
