# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agentcore_metering",
            "0015_llmusage_is_streaming_first_chunk_at",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMUsageSeries",
            fields=[
                ("id", models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name="ID",
                )),
                ("granularity", models.CharField(
                    db_index=True,
                    max_length=10,
                )),
                ("bucket", models.DateTimeField(db_index=True)),
                ("model", models.CharField(db_index=True, max_length=200)),
                ("call_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("avg_e2e_latency_sec", models.FloatField(blank=True, null=True)),
                ("avg_ttft_sec", models.FloatField(blank=True, null=True)),
                ("avg_output_tps", models.FloatField(blank=True, null=True)),
                ("total_prompt_tokens", models.BigIntegerField(default=0)),
                ("total_completion_tokens", models.BigIntegerField(default=0)),
                ("total_tokens", models.BigIntegerField(default=0)),
                ("total_cached_tokens", models.BigIntegerField(default=0)),
                ("total_reasoning_tokens", models.BigIntegerField(default=0)),
                ("total_cost", models.DecimalField(
                    blank=True,
                    decimal_places=6,
                    max_digits=12,
                    null=True,
                )),
                ("cost_currency", models.CharField(
                    blank=True,
                    default="USD",
                    max_length=10,
                )),
            ],
            options={
                "db_table": "llm_usage_series",
                "ordering": ["granularity", "bucket", "model"],
            },
        ),
        migrations.AddConstraint(
            model_name="llmusageseries",
            constraint=models.UniqueConstraint(
                fields=("granularity", "bucket", "model"),
                name="llm_usage_series_unique_bucket_model",
            ),
        ),
        migrations.AddIndex(
            model_name="llmusageseries",
            index=models.Index(
                fields=["granularity", "bucket"],
                name="llm_usage_s_granula_bucket_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmusageseries",
            index=models.Index(
                fields=["granularity", "model", "bucket"],
                name="llm_usage_s_granula_model_bucket_idx",
            ),
        ),
    ]
