# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentcore_metering", "0016_llmusageseries"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeteringConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128)),
                ("value", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agentcore_metering_config",
                "verbose_name": "Metering Config",
                "verbose_name_plural": "Metering Configs",
            },
        ),
        migrations.AddIndex(
            model_name="meteringconfig",
            index=models.Index(
                fields=["scope", "key"],
                name="agentcore_me_scope_key_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="meteringconfig",
            constraint=models.UniqueConstraint(
                fields=("scope", "key"),
                name="agentcore_metering_config_scope_key_uniq",
            ),
        ),
    ]
