# Generated by Django 5.1.4 on 2026-02-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentcore_metering", "0017_meteringconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="llmusageseries",
            options={
                "ordering": ["granularity", "bucket", "model"],
                "verbose_name": "LLM Usage Series",
                "verbose_name_plural": "LLM Usage Series",
            },
        ),
        migrations.RenameIndex(
            model_name="llmusageseries",
            new_name="llm_usage_s_granula_6d2f24_idx",
            old_name="llm_usage_s_granula_bucket_idx",
        ),
        migrations.RenameIndex(
            model_name="llmusageseries",
            new_name="llm_usage_s_granula_491427_idx",
            old_name="llm_usage_s_granula_model_bucket_idx",
        ),
        migrations.RenameIndex(
            model_name="meteringconfig",
            new_name="agentcore_m_scope_c4d6d0_idx",
            old_name="agentcore_me_scope_key_idx",
        ),
        migrations.AlterField(
            model_name="llmusageseries",
            name="bucket",
            field=models.DateTimeField(
                db_index=True, help_text="Truncated time bucket (hour/day/month)."
            ),
        ),
        migrations.AlterField(
            model_name="llmusageseries",
            name="granularity",
            field=models.CharField(
                choices=[
                    ("hour", "Hour (for day view)"),
                    ("day", "Day (for month view)"),
                    ("month", "Month (for year view)"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="meteringconfig",
            name="scope",
            field=models.CharField(
                choices=[("global", "Global")],
                db_index=True,
                default="global",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="meteringconfig",
            name="value",
            field=models.JSONField(
                default=dict, help_text='Config payload, e.g. {"retention_days": 365}.'
            ),
        ),
    ]
