# Generated by Django 5.1.4 on 2026-06-25 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_stack', '0009_monitoringgovernancefinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSshKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='monitoringhost',
            name='ssh_auth_type',
            field=models.CharField(choices=[('key', 'SSH key'), ('password', 'Password')], default='key', max_length=16),
        ),
        migrations.AddField(
            model_name='monitoringhost',
            name='ssh_password',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='monitoringhost',
            name='ssh_key_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='monitoring_stack.monitoringsshkey'),
        ),
    ]
