# Generated by Django 5.1.4 on 2026-08-13 06:05

from django.db import migrations, models


def migrate_host_passwords(apps, schema_editor):
    from monitoring_stack.services.credential_crypto import encrypt_secret

    Credential = apps.get_model("monitoring_stack", "MonitoringSshCredential")
    Version = apps.get_model(
        "monitoring_stack", "MonitoringSshCredentialVersion"
    )
    Host = apps.get_model("monitoring_stack", "MonitoringHost")
    by_password = {}
    for host in Host.objects.filter(
        ssh_auth_type="password", ssh_password__gt=""
    ).order_by("id"):
        password = str(host.ssh_password)
        credential = by_password.get(password)
        if credential is None:
            base_name = f"migrated-{host.hostname or host.id}-password"[:120]
            name = base_name
            suffix = 2
            while Credential.objects.filter(name=name).exclude(
                status="archived"
            ).exists():
                tail = f"-{suffix}"
                name = f"{base_name[:120-len(tail)]}{tail}"
                suffix += 1
            credential = Credential.objects.create(
                name=name,
                credential_type="password",
                status="active",
            )
            version = Version.objects.create(
                credential=credential,
                version=1,
                secret_encrypted=encrypt_secret(password),
                algorithm="password",
                validation_status="valid",
            )
            credential.active_version_id = version.id
            credential.save(update_fields=["active_version"])
            by_password[password] = credential
        host.ssh_key_credential_id = credential.id
        host.ssh_password = ""
        host.save(update_fields=["ssh_key_credential", "ssh_password"])


def restore_host_passwords(apps, schema_editor):
    from monitoring_stack.services.credential_crypto import decrypt_secret

    Host = apps.get_model("monitoring_stack", "MonitoringHost")
    for host in Host.objects.filter(
        ssh_auth_type="password", ssh_key_credential__credential_type="password"
    ).select_related("ssh_key_credential__active_version"):
        version = host.ssh_key_credential.active_version
        if not version or not version.secret_encrypted:
            continue
        host.ssh_password = decrypt_secret(version.secret_encrypted)
        host.ssh_key_credential_id = None
        host.save(update_fields=["ssh_password", "ssh_key_credential"])


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_stack', '0016_ssh_credential_center_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsshcredential',
            name='credential_type',
            field=models.CharField(choices=[('private_key', 'SSH private key'), ('password', 'Password')], default='private_key', max_length=24),
        ),
        migrations.AddField(
            model_name='monitoringsshcredentialversion',
            name='secret_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monitoringsshcredentialversion',
            name='algorithm',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='monitoringsshcredentialversion',
            name='private_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monitoringsshcredentialversion',
            name='public_key_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='monitoringsshcredentialversion',
            name='public_key_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(migrate_host_passwords, restore_host_passwords),
    ]
