# Generated by Django 5.1.4 on 2026-05-13 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('url', models.URLField(verbose_name='Jenkins URL')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('token', models.CharField(max_length=512, verbose_name='API Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Jenkins 实例',
                'verbose_name_plural': 'Jenkins 实例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriggerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='显示名称')),
                ('job_name', models.CharField(max_length=512, verbose_name='Jenkins Job 名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('params_config', models.JSONField(default=dict, help_text="每个参数的 mode 和预设值，格式: {param_name: {mode: 'hidden'|'readonly'|'editable', default_value: 'xxx'}}", verbose_name='参数配置')),
                ('notify_enabled', models.BooleanField(default=False, verbose_name='是否发送通知')),
                ('notify_emails', models.JSONField(default=list, help_text='通知人邮箱列表', verbose_name='通知人邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_entries', to='jenkins_trigger.jenkinsinstance', verbose_name='Jenkins 实例')),
            ],
            options={
                'verbose_name': '触发入口',
                'verbose_name_plural': '触发入口',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriggerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(default=dict, verbose_name='触发参数')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '构建中'), ('success', '成功'), ('failure', '失败'), ('aborted', '取消')], default='pending', max_length=20, verbose_name='状态')),
                ('build_number', models.IntegerField(blank=True, null=True, verbose_name='Build Number')),
                ('artifacts', models.JSONField(default=list, verbose_name='构建产物')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='jenkins_trigger.triggerentry', verbose_name='触发入口')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_records', to=settings.AUTH_USER_MODEL, verbose_name='触发用户')),
            ],
            options={
                'verbose_name': '触发记录',
                'verbose_name_plural': '触发记录',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
