# Generated by Django 5.1.4 on 2026-05-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jenkins_trigger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JenkinsGlobalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_catalog_cache_ttl_seconds",
                    models.PositiveIntegerField(
                        default=86400,
                        verbose_name="Job 列表缓存时长（秒）",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Jenkins 全局配置",
                "verbose_name_plural": "Jenkins 全局配置",
            },
        ),
    ]
