# Generated by Django 5.1.4 on 2026-05-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jenkins_trigger", "0002_jenkinsglobalconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="jenkinsinstance",
            name="job_catalog_cache_ttl_days",
            field=models.PositiveIntegerField(
                default=1,
                verbose_name="Job 列表缓存时长（天）",
            ),
        ),
    ]
