# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jenkins_trigger", "0003_jenkinsinstance_job_catalog_cache_ttl_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="triggerrecord",
            name="queue_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="Jenkins Queue URL",
            ),
        ),
    ]
