# Generated by Django 5.1.4 on 2026-06-15 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_trigger', '0007_triggerrecord_pipeline_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsResourceLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='标签名称')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='标签标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Jenkins 资源标签',
                'verbose_name_plural': 'Jenkins 资源标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JenkinsJobIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, verbose_name='Job 完整名称')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='最近一次出现时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_identities', to='jenkins_trigger.jenkinsinstance', verbose_name='Jenkins 实例')),
                ('labels', models.ManyToManyField(blank=True, related_name='jobs', to='jenkins_trigger.jenkinsresourcelabel', verbose_name='资源标签')),
            ],
            options={
                'verbose_name': 'Jenkins Job 身份',
                'verbose_name_plural': 'Jenkins Job 身份',
                'ordering': ['full_name'],
                'unique_together': {('instance', 'full_name')},
            },
        ),
    ]
