# Generated by Django 5.1.4 on 2026-08-31 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageAccessKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("access_key_id_encrypted", models.TextField()),
                ("secret_access_key_encrypted", models.TextField()),
                ("access_key_fingerprint", models.CharField(max_length=128)),
                ("access_key_last_four", models.CharField(max_length=4)),
                (
                    "cloud_state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("deleted", "Deleted"),
                            ("unknown", "Unknown"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "local_state",
                    models.CharField(
                        choices=[
                            ("issuing", "Issuing"),
                            ("delivery_ready", "Delivery ready"),
                            ("active", "Active"),
                            ("retiring", "Retiring"),
                            ("retired", "Retired"),
                            ("error", "Error"),
                        ],
                        default="issuing",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["tenant_id", "cloud_identity_id", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=63)),
                ("project", models.CharField(max_length=80)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("test", "Test"),
                            ("production", "Production"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purpose", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("region", models.CharField(max_length=80)),
                ("template_version", models.PositiveIntegerField(default=1)),
                (
                    "cloud_resource_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "cloud_marker",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("creating", "Creating"),
                            ("active", "Active"),
                            ("releasing", "Releasing"),
                            ("released", "Released"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["tenant_id", "owner_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="StorageCloudIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ram_user_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ram_user_name", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("error", "Error"),
                        ],
                        default="provisioning",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["tenant_id", "membership_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="StorageResourcePool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("aliyun", "Alibaba Cloud")],
                        default="aliyun",
                        max_length=20,
                    ),
                ),
                ("cloud_account_id", models.CharField(max_length=160)),
                ("region", models.CharField(max_length=80)),
                ("management_access_key_encrypted", models.TextField()),
                ("management_secret_key_encrypted", models.TextField()),
                ("credential_fingerprint", models.CharField(max_length=128)),
                ("access_key_last_four", models.CharField(max_length=4)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "validation_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["tenant_id", "provider", "id"],
            },
        ),
        migrations.CreateModel(
            name="StorageApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            (
                                "first_bucket_and_credential",
                                "First bucket and credential",
                            ),
                            ("add_bucket", "Add bucket"),
                            ("rotate_credential", "Rotate credential"),
                            ("release_bucket", "Release bucket"),
                            ("suspend_membership", "Suspend membership"),
                            ("reactivate_membership", "Reactivate membership"),
                        ],
                        max_length=40,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_fields", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("delivery_ready", "Delivery ready"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("manual_required", "Manual required"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_summary",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_access_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="object_storage.storageaccesskey",
                    ),
                ),
                (
                    "target_bucket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="object_storage.storagebucket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StorageApplicationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "provider_request_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="object_storage.storageapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["application_id", "attempt_number"],
            },
        ),
        migrations.AddField(
            model_name="storagebucket",
            name="cloud_identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buckets",
                to="object_storage.storagecloudidentity",
            ),
        ),
        migrations.AddField(
            model_name="storageaccesskey",
            name="cloud_identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_keys",
                to="object_storage.storagecloudidentity",
            ),
        ),
        migrations.CreateModel(
            name="StorageMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feishu_open_id", models.CharField(max_length=255)),
                (
                    "feishu_union_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("display_name", models.CharField(max_length=160)),
                ("department_snapshot", models.JSONField(blank=True, default=list)),
                ("profile_snapshot", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="object_storage_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["tenant_id", "display_name", "id"],
            },
        ),
        migrations.AddField(
            model_name="storagecloudidentity",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cloud_identities",
                to="object_storage.storagemembership",
            ),
        ),
        migrations.AddField(
            model_name="storagebucket",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buckets",
                to="object_storage.storagemembership",
            ),
        ),
        migrations.AddField(
            model_name="storageapplication",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="object_storage.storagemembership",
            ),
        ),
        migrations.AddField(
            model_name="storagecloudidentity",
            name="resource_pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cloud_identities",
                to="object_storage.storageresourcepool",
            ),
        ),
        migrations.AddField(
            model_name="storagebucket",
            name="resource_pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buckets",
                to="object_storage.storageresourcepool",
            ),
        ),
        migrations.CreateModel(
            name="StorageTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "bucket_naming_template",
                    models.CharField(
                        default="{tenant}-{user}-{project}-{environment}-{suffix}",
                        max_length=255,
                    ),
                ),
                ("naming_template_version", models.PositiveIntegerField(default=1)),
                ("default_bucket_quota", models.PositiveSmallIntegerField(default=5)),
                (
                    "delivery_lifetime_seconds",
                    models.PositiveIntegerField(default=86400),
                ),
                ("audit_retention_days", models.PositiveSmallIntegerField(default=30)),
            ],
            options={
                "ordering": ["name", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("default_bucket_quota__gte", 1)),
                        name="storage_tenant_quota_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("delivery_lifetime_seconds__gte", 600),
                            ("delivery_lifetime_seconds__lte", 604800),
                        ),
                        name="storage_tenant_delivery_lifetime_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("audit_retention_days", 30)),
                        name="storage_tenant_audit_retention_phase_one",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="storageresourcepool",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resource_pools",
                to="object_storage.storagetenant",
            ),
        ),
        migrations.AddField(
            model_name="storagemembership",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="object_storage.storagetenant",
            ),
        ),
        migrations.CreateModel(
            name="StorageDeliveryTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_digest", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="ready",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_tickets",
                        to="object_storage.storageaccesskey",
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_ticket",
                        to="object_storage.storageapplication",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_tickets",
                        to="object_storage.storagemembership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_tickets",
                        to="object_storage.storagetenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="storagecloudidentity",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cloud_identities",
                to="object_storage.storagetenant",
            ),
        ),
        migrations.AddField(
            model_name="storagebucket",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buckets",
                to="object_storage.storagetenant",
            ),
        ),
        migrations.CreateModel(
            name="StorageAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=120)),
                ("target_type", models.CharField(max_length=120)),
                ("target_id", models.CharField(max_length=255)),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "request_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("result", models.CharField(max_length=64)),
                ("safe_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="object_storage_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="object_storage.storageapplication",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="object_storage.storagetenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StorageApplicationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=48)),
                ("result", models.CharField(max_length=24)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("safe_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="object_storage.storageapplication",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="object_storage.storageapplicationattempt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_events",
                        to="object_storage.storagetenant",
                    ),
                ),
            ],
            options={
                "ordering": ["application_id", "created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="storageapplicationattempt",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="application_attempts",
                to="object_storage.storagetenant",
            ),
        ),
        migrations.AddField(
            model_name="storageapplication",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="object_storage.storagetenant",
            ),
        ),
        migrations.AddField(
            model_name="storageaccesskey",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_keys",
                to="object_storage.storagetenant",
            ),
        ),
        migrations.CreateModel(
            name="FeishuAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_id", models.CharField(max_length=160)),
                ("app_secret_encrypted", models.TextField()),
                ("oauth_callback_url", models.URLField(max_length=512)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "validation_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feishu_app_config",
                        to="object_storage.storagetenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant_id"],
            },
        ),
        migrations.AddIndex(
            model_name="storageresourcepool",
            index=models.Index(
                fields=["tenant", "provider", "enabled"],
                name="os_pool_tenant_provider_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storageresourcepool",
            constraint=models.UniqueConstraint(
                condition=models.Q(("enabled", True)),
                fields=("tenant", "provider"),
                name="storage_pool_one_enabled_provider",
            ),
        ),
        migrations.AddIndex(
            model_name="storagemembership",
            index=models.Index(
                fields=["tenant", "is_active"], name="os_member_tenant_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storagemembership",
            index=models.Index(
                fields=["tenant", "feishu_union_id"], name="os_member_tenant_union_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storagemembership",
            constraint=models.UniqueConstraint(
                fields=("tenant", "feishu_open_id"),
                name="storage_member_tenant_open_id_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="storagedeliveryticket",
            index=models.Index(
                fields=["tenant", "membership", "status", "expires_at"],
                name="os_ticket_member_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storagecloudidentity",
            index=models.Index(
                fields=["tenant", "membership", "state"],
                name="os_identity_member_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagecloudidentity",
            constraint=models.UniqueConstraint(
                fields=("tenant", "membership", "resource_pool"),
                name="storage_identity_member_pool_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagecloudidentity",
            constraint=models.UniqueConstraint(
                fields=("resource_pool", "ram_user_name"),
                name="storage_identity_pool_ram_name_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="storagebucket",
            index=models.Index(
                fields=["tenant", "owner", "state"], name="os_bucket_owner_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storagebucket",
            index=models.Index(
                fields=["resource_pool", "state"], name="os_bucket_pool_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storagebucket",
            constraint=models.UniqueConstraint(
                fields=("resource_pool", "name"), name="storage_bucket_pool_name_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="storageauditevent",
            index=models.Index(
                fields=["tenant", "-created_at"], name="os_audit_tenant_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storageauditevent",
            index=models.Index(
                fields=["tenant", "action", "-created_at"],
                name="os_audit_tenant_action_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storageapplicationevent",
            index=models.Index(
                fields=["tenant", "application", "created_at"],
                name="os_event_application_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storageapplicationattempt",
            index=models.Index(
                fields=["tenant", "status", "-started_at"],
                name="os_attempt_tenant_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storageapplicationattempt",
            constraint=models.UniqueConstraint(
                fields=("application", "attempt_number"),
                name="storage_attempt_number_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="storageapplication",
            index=models.Index(
                fields=["tenant", "applicant", "status", "-created_at"],
                name="os_app_applicant_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storageapplication",
            index=models.Index(
                fields=["tenant", "status", "-created_at"],
                name="os_app_tenant_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storageapplication",
            constraint=models.UniqueConstraint(
                fields=("tenant", "applicant", "idempotency_key"),
                name="storage_application_idempotency_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="storageaccesskey",
            index=models.Index(
                fields=["tenant", "cloud_identity", "local_state"],
                name="os_key_identity_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storageaccesskey",
            constraint=models.UniqueConstraint(
                fields=("tenant", "access_key_fingerprint"),
                name="storage_key_tenant_fingerprint_unique",
            ),
        ),
    ]
