# Generated by Django 5.1.4 on 2026-09-01 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class CreateDefaultPlatformObjectStorageConfig(Operation):
    """Bootstrap the fixed FK target before preserving legacy pool rows."""

    reduces_to_sql = False
    reversible = True

    def state_forwards(self, app_label, state):
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        config_model = from_state.apps.get_model(
            app_label, "PlatformObjectStorageConfig"
        )
        config_model.objects.using(schema_editor.connection.alias).get_or_create(
            pk=1,
            defaults={
                "singleton_key": "default",
                "naming_template": (
                    "hyperops-{user}-{business_name}-{environment}-{suffix}"
                ),
                "naming_template_version": 1,
                "default_bucket_quota": 5,
                "delivery_lifetime_seconds": 86400,
                "audit_retention_days": 30,
                "pause_new_applications": True,
                "pause_key_operations": True,
            },
        )

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        config_model = from_state.apps.get_model(
            app_label, "PlatformObjectStorageConfig"
        )
        config_model.objects.using(schema_editor.connection.alias).filter(
            pk=1,
            singleton_key="default",
        ).delete()

    def describe(self):
        return "Create the safe default platform object-storage configuration"


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("object_storage", "0004_feishu_access_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("access_key_id_encrypted", models.TextField()),
                ("secret_access_key_encrypted", models.TextField()),
                ("access_key_fingerprint", models.CharField(max_length=128)),
                ("access_key_last_four", models.CharField(max_length=4)),
                (
                    "cloud_state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("deleted", "Deleted"),
                            ("unknown", "Unknown"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "local_state",
                    models.CharField(
                        choices=[
                            ("issuing", "Issuing"),
                            ("delivery_ready", "Delivery ready"),
                            ("active", "Active"),
                            ("retiring", "Retiring"),
                            ("retired", "Retired"),
                            ("error", "Error"),
                        ],
                        default="issuing",
                        max_length=24,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["cloud_identity_id", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_request_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "ordering": ["application_item_id", "attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partially_succeeded", "Partially succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("manual_required", "Manual required"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                ("item_count", models.PositiveSmallIntegerField(default=0)),
                ("pending_count", models.PositiveSmallIntegerField(default=0)),
                ("success_count", models.PositiveSmallIntegerField(default=0)),
                ("failed_count", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_summary",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=48)),
                ("result", models.CharField(max_length=24)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("safe_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["application_item_id", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(max_length=80)),
                ("project", models.CharField(blank=True, default="", max_length=80)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("test", "Test"),
                            ("production", "Production"),
                        ],
                        default="development",
                        max_length=20,
                    ),
                ),
                ("purpose", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("rendered_bucket_name", models.CharField(max_length=63)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("creating", "Creating"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("releasing", "Releasing"),
                            ("pending_delete", "Pending delete"),
                            ("delete_blocked", "Delete blocked"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_summary",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "ordering": ["batch_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_id_snapshot",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "actor_name_snapshot",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("action", models.CharField(max_length=120)),
                ("target_type", models.CharField(max_length=120)),
                ("target_id", models.CharField(max_length=255)),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "request_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("result", models.CharField(max_length=64)),
                ("safe_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Bucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=63)),
                ("project", models.CharField(blank=True, default="", max_length=80)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("test", "Test"),
                            ("production", "Production"),
                        ],
                        default="development",
                        max_length=20,
                    ),
                ),
                ("purpose", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("region", models.CharField(max_length=80)),
                ("template_version", models.PositiveIntegerField(default=1)),
                ("config_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "cloud_resource_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "cloud_marker",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("creating", "Creating"),
                            ("waiting_retry", "Waiting retry"),
                            ("active", "Active"),
                            ("releasing", "Releasing"),
                            ("pending_deletion", "Pending deletion"),
                            ("deletion_blocked", "Deletion blocked"),
                            ("released", "Released"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("pending_delete_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["owner_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="CloudIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ram_user_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ram_user_name", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("error", "Error"),
                        ],
                        default="provisioning",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["user_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_digest", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="ready",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FeishuIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("open_id", models.CharField(max_length=255, unique=True)),
                (
                    "union_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("display_name", models.CharField(max_length=160)),
                ("department_snapshot", models.JSONField(blank=True, default=list)),
                ("profile_snapshot", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["display_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PlatformFeishuConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "singleton_key",
                    models.CharField(default="default", max_length=32, unique=True),
                ),
                ("app_id", models.CharField(blank=True, default="", max_length=160)),
                ("app_secret_encrypted", models.TextField(blank=True, default="")),
                (
                    "oauth_callback_url",
                    models.URLField(blank=True, default="", max_length=512),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "validation_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["singleton_key"],
            },
        ),
        migrations.CreateModel(
            name="PlatformObjectStorageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "singleton_key",
                    models.CharField(default="default", max_length=32, unique=True),
                ),
                (
                    "naming_template",
                    models.CharField(
                        default="hyperops-{user}-{business_name}-{environment}-{suffix}",
                        max_length=255,
                    ),
                ),
                ("naming_template_version", models.PositiveIntegerField(default=1)),
                ("default_bucket_quota", models.PositiveSmallIntegerField(default=5)),
                (
                    "delivery_lifetime_seconds",
                    models.PositiveIntegerField(default=86400),
                ),
                ("audit_retention_days", models.PositiveSmallIntegerField(default=30)),
                ("pause_new_applications", models.BooleanField(default=True)),
                ("pause_key_operations", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["singleton_key"],
            },
        ),
        CreateDefaultPlatformObjectStorageConfig(),
        migrations.RemoveConstraint(
            model_name="storageresourcepool",
            name="storage_pool_one_enabled_provider",
        ),
        migrations.RemoveIndex(
            model_name="storageresourcepool",
            name="os_pool_tenant_provider_idx",
        ),
        migrations.RemoveField(
            model_name="storageresourcepool",
            name="tenant",
        ),
        migrations.AlterModelOptions(
            name="storageresourcepool",
            options={"ordering": ["provider", "id"]},
        ),
        migrations.AddField(
            model_name="applicationbatch",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="object_storage_application_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="applicationevent",
            name="attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="object_storage.applicationattempt",
            ),
        ),
        migrations.AddField(
            model_name="applicationitem",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="object_storage.applicationbatch",
            ),
        ),
        migrations.AddField(
            model_name="applicationevent",
            name="application_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="object_storage.applicationitem",
            ),
        ),
        migrations.AddField(
            model_name="applicationattempt",
            name="application_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="object_storage.applicationitem",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="object_storage_audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bucket",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="object_storage_buckets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bucket",
            name="resource_pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buckets",
                to="object_storage.storageresourcepool",
            ),
        ),
        migrations.AddField(
            model_name="applicationitem",
            name="bucket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="application_items",
                to="object_storage.bucket",
            ),
        ),
        migrations.AddField(
            model_name="cloudidentity",
            name="resource_pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cloud_identities",
                to="object_storage.storageresourcepool",
            ),
        ),
        migrations.AddField(
            model_name="cloudidentity",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="object_storage_cloud_identity",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bucket",
            name="cloud_identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buckets",
                to="object_storage.cloudidentity",
            ),
        ),
        migrations.AddField(
            model_name="accesskey",
            name="cloud_identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_keys",
                to="object_storage.cloudidentity",
            ),
        ),
        migrations.AddField(
            model_name="deliveryticket",
            name="access_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_tickets",
                to="object_storage.accesskey",
            ),
        ),
        migrations.AddField(
            model_name="deliveryticket",
            name="application_batch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_ticket",
                to="object_storage.applicationbatch",
            ),
        ),
        migrations.AddField(
            model_name="deliveryticket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="object_storage_delivery_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feishuidentity",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feishu_identity",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="platformfeishuconfig",
            name="access_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Local group whose roles are granted to users signing in through Feishu.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="platform_feishu_configs",
                to="auth.group",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformfeishuconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("singleton_key", "default")),
                name="storage_feishu_singleton_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformobjectstorageconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("singleton_key", "default")),
                name="storage_object_singleton_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformobjectstorageconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_bucket_quota__gte", 1)),
                name="storage_platform_quota_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformobjectstorageconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_lifetime_seconds__gte", 600),
                    ("delivery_lifetime_seconds__lte", 604800),
                ),
                name="storage_platform_delivery_lifetime_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="platformobjectstorageconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("audit_retention_days__gte", 1),
                    ("audit_retention_days__lte", 3650),
                ),
                name="storage_platform_audit_retention_range",
            ),
        ),
        migrations.AddField(
            model_name="storageresourcepool",
            name="config",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resource_pools",
                to="object_storage.platformobjectstorageconfig",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="storageresourcepool",
            index=models.Index(
                fields=["provider", "enabled"], name="os_pool_provider_enabled_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storageresourcepool",
            constraint=models.UniqueConstraint(
                condition=models.Q(("enabled", True)),
                fields=("provider",),
                name="storage_pool_one_enabled_provider",
            ),
        ),
        migrations.DeleteModel(
            name="StorageApplicationEvent",
        ),
        migrations.DeleteModel(
            name="StorageApplicationAttempt",
        ),
        migrations.DeleteModel(
            name="StorageAuditEvent",
        ),
        migrations.DeleteModel(
            name="StorageDeliveryTicket",
        ),
        migrations.DeleteModel(
            name="StorageApplication",
        ),
        migrations.DeleteModel(
            name="StorageAccessKey",
        ),
        migrations.DeleteModel(
            name="StorageBucket",
        ),
        migrations.DeleteModel(
            name="StorageCloudIdentity",
        ),
        migrations.DeleteModel(
            name="FeishuAppConfig",
        ),
        migrations.DeleteModel(
            name="StorageMembership",
        ),
        migrations.DeleteModel(
            name="StorageTenant",
        ),
        migrations.AddIndex(
            model_name="applicationbatch",
            index=models.Index(
                fields=["applicant", "status", "-created_at"],
                name="os_batch_applicant_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationbatch",
            index=models.Index(
                fields=["status", "-created_at"], name="os_batch_status_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationbatch",
            constraint=models.UniqueConstraint(
                fields=("applicant", "idempotency_key"),
                name="storage_batch_applicant_idempotency_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationevent",
            index=models.Index(
                fields=["application_item", "created_at"], name="os_event_item_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationattempt",
            index=models.Index(
                fields=["status", "-started_at"], name="os_attempt_status_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationattempt",
            constraint=models.UniqueConstraint(
                fields=("application_item", "attempt_number"),
                name="storage_attempt_number_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["-created_at"], name="os_audit_time_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["action", "-created_at"], name="os_audit_action_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationitem",
            index=models.Index(
                fields=["batch", "status"], name="os_item_batch_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "rendered_bucket_name"),
                name="storage_item_batch_bucket_name_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="cloudidentity",
            index=models.Index(
                fields=["user", "state"], name="os_identity_user_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cloudidentity",
            constraint=models.UniqueConstraint(
                fields=("resource_pool", "ram_user_name"),
                name="storage_identity_pool_ram_name_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="bucket",
            index=models.Index(
                fields=["owner", "state"], name="os_bucket_owner_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucket",
            index=models.Index(
                fields=["resource_pool", "state"], name="os_bucket_pool_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucket",
            index=models.Index(
                fields=["state", "pending_delete_at"],
                name="os_bucket_pending_delete_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bucket",
            constraint=models.UniqueConstraint(
                fields=("resource_pool", "name"), name="storage_bucket_pool_name_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="accesskey",
            index=models.Index(
                fields=["cloud_identity", "local_state"],
                name="os_key_identity_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesskey",
            constraint=models.UniqueConstraint(
                fields=("cloud_identity", "access_key_fingerprint"),
                name="storage_access_key_fingerprint_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryticket",
            index=models.Index(
                fields=["user", "status", "expires_at"],
                name="os_ticket_user_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feishuidentity",
            index=models.Index(
                fields=["is_active", "display_name"], name="os_feishu_active_name_idx"
            ),
        ),
    ]
