# Generated by Django 5.1.4 on 2026-09-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0005_platform_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBucketQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bucket_quota", models.PositiveSmallIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="object_storage_bucket_quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("bucket_quota__gte", 1)),
                        name="storage_user_bucket_quota_positive",
                    )
                ],
            },
        ),
    ]
