# Generated by Django 5.1.4 on 2026-09-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0006_user_bucket_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationbatch",
            name="payload_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="applicationbatch",
            name="issued_access_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_for_application_batches",
                to="object_storage.accesskey",
            ),
        ),
        migrations.AddField(
            model_name="applicationitem",
            name="initial_suffix",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="applicationitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("creating", "Creating"),
                    ("waiting_retry", "Waiting retry"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("manual_required", "Manual required"),
                    ("releasing", "Releasing"),
                    ("pending_delete", "Pending delete"),
                    ("delete_blocked", "Delete blocked"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("task_id", ""), _negated=True),
                fields=("application_item", "task_id"),
                name="storage_attempt_item_task_unique",
            ),
        ),
        migrations.AddField(
            model_name="deliveryticket",
            name="token_rotated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
