# Generated by Django 5.1.4 on 2026-09-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0007_batch_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationbatch",
            name="cloud_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="application_batches",
                to="object_storage.cloudidentity",
            ),
        ),
        migrations.AddField(
            model_name="applicationbatch",
            name="identity_created_by_batch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="applicationbatch",
            name="principal_created_by_batch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="applicationbatch",
            name="key_created_by_batch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="applicationbatch",
            name="running_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="applicationbatch",
            name="run_lease_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
