# Generated by Django 5.1.4 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0008_batch_safety_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationbatch",
            name="owner_token",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="applicationbatch",
            index=models.Index(
                fields=["status", "run_lease_until"],
                name="os_batch_claim_lease_idx",
            ),
        ),
    ]
