# Generated by Django 5.1.4 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0009_application_claim_fencing"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationbatch",
            name="claim_version",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
