# Generated by Django 5.1.4 on 2026-02-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentcore_task_tracker', '0003_taskconfig'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskconfig',
            new_name='agentcore_t_scope_e6f9ab_idx',
            old_name='agentcore_task_config_scope_key_idx',
        ),
        migrations.RenameIndex(
            model_name='taskexecution',
            new_name='agentcore_t_module_41d356_idx',
            old_name='agentcore_t_module_7a8b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='taskexecution',
            new_name='agentcore_t_task_na_422347_idx',
            old_name='agentcore_t_task_na_9c4d1e_idx',
        ),
        migrations.RenameIndex(
            model_name='taskexecution',
            new_name='agentcore_t_created_5966dc_idx',
            old_name='agentcore_t_created_2f3a5b_idx',
        ),
        migrations.RenameIndex(
            model_name='taskexecution',
            new_name='agentcore_t_status_c92dcd_idx',
            old_name='agentcore_t_status_1b6c9d_idx',
        ),
        migrations.RenameIndex(
            model_name='taskexecution',
            new_name='agentcore_t_module_b399e5_idx',
            old_name='agentcore_t_module_4e5f6a_idx',
        ),
        migrations.RenameIndex(
            model_name='taskexecution',
            new_name='agentcore_t_created_df1ca4_idx',
            old_name='agentcore_t_created_8d7e0f_idx',
        ),
        migrations.RenameIndex(
            model_name='taskexecution',
            new_name='agentcore_t_created_16b5f7_idx',
            old_name='agentcore_t_created_3c2b1a_idx',
        ),
    ]
