# Generated by Django 5.1.4 on 2026-06-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_orchestration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actionstep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='actionstep',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='actionstep',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('template', 'order'), name='unique_active_action_step_order'),
        ),
    ]
