# Generated by Django 5.1.4 on 2026-06-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_orchestration', '0002_alter_actionstep_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstep',
            name='action_type',
            field=models.CharField(choices=[('jenkins_trigger', 'Jenkins trigger'), ('gitlab_branch_create', 'GitLab branch create'), ('gitlab_branch_operation', 'GitLab branch operation'), ('gitlab_tag_operation', 'GitLab tag operation'), ('gitlab_webhook_operation', 'GitLab webhook operation'), ('manual_approval', 'Manual approval'), ('conditional_branch', 'Conditional branch')], max_length=64),
        ),
    ]
