from django.urls import path

from object_storage.views_admin import (
    AccessGroupListView,
    AccessKeyAdminDetailView,
    AccessKeyAdminListView,
    AccessKeyDisableView,
    AccessKeyEnableView,
    AccessKeyRevealView,
    AccessKeyRevokeView,
    AccessKeyRotateView,
    ApplicationBatchAdminDetailView,
    ApplicationBatchAdminListView,
    ApplicationBatchRetryView,
    IdempotencyRecordAdminDetailView,
    IdempotencyRecordAdminListView,
    IdempotencyRecordAdminResolveView,
    AuditEventAdminDetailView,
    AuditEventAdminListView,
    BucketActionUncertaintyAcknowledgeView,
    BucketActionUncertaintyObserveView,
    BucketAdminDetailView,
    BucketAdminListView,
    BucketConfigurationRetryView,
    BucketConfigurationUncertaintyAcknowledgeView,
    BucketConfigurationUncertaintyObserveView,
    BucketConfigurationView,
    BucketDeleteView,
    BucketRecoverView,
    BucketReleaseView,
    BucketRetryDeleteView,
    CloudIdentityAdminDetailView,
    CloudIdentityAdminListView,
    CredentialUncertaintyAcknowledgeView,
    CredentialUncertaintyObserveView,
    PlatformFeishuSettingsView,
    PlatformFeishuValidationView,
    PlatformSettingsView,
    StorageResourcePoolDetailView,
    StorageResourcePoolListCreateView,
    StorageResourcePoolValidationView,
    UserQuotaDetailView,
    UserQuotaListView,
    UserResourceReactivateView,
    UserResourceSuspendView,
)
from object_storage.views_auth import (
    FeishuCallbackView,
    FeishuLoginStartView,
    HandoffExchangeView,
)
from object_storage.views_employee import (
    EmployeeApplicationDetailView,
    EmployeeApplicationItemCancelView,
    EmployeeApplicationItemRetryView,
    EmployeeApplicationListCreateView,
    EmployeeBucketDetailView,
    EmployeeBucketListView,
    EmployeeBucketRecoverView,
    EmployeeBucketReleaseView,
    EmployeeCredentialDeliveryView,
    EmployeeCredentialDetailView,
    EmployeeCredentialDisableView,
    EmployeeCredentialEnableView,
    EmployeeCredentialListView,
    EmployeeCredentialRevokeView,
    EmployeeCredentialRotateView,
    EmployeeOverviewView,
)
from object_storage.views_feishu_admin import (
    FeishuSyncConfirmView,
    FeishuSyncPreviewView,
)

app_name = "object_storage"


urlpatterns = [
    path(
        "auth/feishu/start/", FeishuLoginStartView.as_view(), name="feishu_login_start"
    ),
    path("auth/feishu/callback/", FeishuCallbackView.as_view(), name="feishu_callback"),
    path(
        "auth/handoff/exchange/", HandoffExchangeView.as_view(), name="handoff_exchange"
    ),
    path(
        "workspace/overview/", EmployeeOverviewView.as_view(), name="workspace_overview"
    ),
    path(
        "workspace/buckets/", EmployeeBucketListView.as_view(), name="workspace_buckets"
    ),
    path(
        "workspace/buckets/<int:bucket_id>/",
        EmployeeBucketDetailView.as_view(),
        name="workspace_bucket_detail",
    ),
    path(
        "workspace/buckets/<int:bucket_id>/release/",
        EmployeeBucketReleaseView.as_view(),
        name="workspace_bucket_release",
    ),
    path(
        "workspace/buckets/<int:bucket_id>/recover/",
        EmployeeBucketRecoverView.as_view(),
        name="workspace_bucket_recover",
    ),
    path(
        "workspace/applications/",
        EmployeeApplicationListCreateView.as_view(),
        name="workspace_applications",
    ),
    path(
        "workspace/applications/<int:application_id>/",
        EmployeeApplicationDetailView.as_view(),
        name="workspace_application_detail",
    ),
    path(
        "workspace/applications/<int:application_id>/items/<int:item_id>/retry/",
        EmployeeApplicationItemRetryView.as_view(),
        name="workspace_application_item_retry",
    ),
    path(
        "workspace/applications/<int:application_id>/items/<int:item_id>/cancel/",
        EmployeeApplicationItemCancelView.as_view(),
        name="workspace_application_item_cancel",
    ),
    path(
        "workspace/credentials/",
        EmployeeCredentialListView.as_view(),
        name="workspace_credentials",
    ),
    path(
        "workspace/credentials/<int:key_id>/",
        EmployeeCredentialDetailView.as_view(),
        name="workspace_credential_detail",
    ),
    path(
        "workspace/credentials/<int:key_id>/deliver/",
        EmployeeCredentialDeliveryView.as_view(),
        name="workspace_credential_delivery",
    ),
    path(
        "workspace/credentials/<int:key_id>/disable/",
        EmployeeCredentialDisableView.as_view(),
        name="workspace_credential_disable",
    ),
    path(
        "workspace/credentials/<int:key_id>/enable/",
        EmployeeCredentialEnableView.as_view(),
        name="workspace_credential_enable",
    ),
    path(
        "workspace/credentials/<int:key_id>/rotate/",
        EmployeeCredentialRotateView.as_view(),
        name="workspace_credential_rotate",
    ),
    path(
        "workspace/credentials/<int:key_id>/revoke/",
        EmployeeCredentialRevokeView.as_view(),
        name="workspace_credential_revoke",
    ),
    path(
        "management/settings/",
        PlatformSettingsView.as_view(),
        name="management_settings",
    ),
    path(
        "management/feishu-settings/",
        PlatformFeishuSettingsView.as_view(),
        name="management_feishu_settings",
    ),
    path(
        "management/feishu-settings/validate/",
        PlatformFeishuValidationView.as_view(),
        name="management_feishu_validate",
    ),
    path(
        "management/feishu/sync/preview/",
        FeishuSyncPreviewView.as_view(),
        name="management_feishu_sync_preview",
    ),
    path(
        "management/feishu/sync/confirm/",
        FeishuSyncConfirmView.as_view(),
        name="management_feishu_sync_confirm",
    ),
    path(
        "management/access-groups/",
        AccessGroupListView.as_view(),
        name="management_access_groups",
    ),
    path(
        "management/resource-pools/",
        StorageResourcePoolListCreateView.as_view(),
        name="management_resource_pools",
    ),
    path(
        "management/resource-pools/<int:pool_id>/",
        StorageResourcePoolDetailView.as_view(),
        name="management_resource_pool_detail",
    ),
    path(
        "management/resource-pools/<int:pool_id>/validate/",
        StorageResourcePoolValidationView.as_view(),
        name="management_resource_pool_validate",
    ),
    path(
        "management/user-quotas/",
        UserQuotaListView.as_view(),
        name="management_user_quotas",
    ),
    path(
        "management/user-quotas/<int:user_id>/",
        UserQuotaDetailView.as_view(),
        name="management_user_quota_detail",
    ),
    path(
        "management/cloud-identities/",
        CloudIdentityAdminListView.as_view(),
        name="management_cloud_identities",
    ),
    path(
        "management/cloud-identities/<int:identity_id>/",
        CloudIdentityAdminDetailView.as_view(),
        name="management_cloud_identity_detail",
    ),
    path(
        "management/cloud-identities/<int:identity_id>/uncertainty/observe/",
        CredentialUncertaintyObserveView.as_view(),
        name="management_credential_uncertainty_observe",
    ),
    path(
        "management/cloud-identities/<int:identity_id>/uncertainty/acknowledge/",
        CredentialUncertaintyAcknowledgeView.as_view(),
        name="management_credential_uncertainty_acknowledge",
    ),
    path(
        "management/buckets/", BucketAdminListView.as_view(), name="management_buckets"
    ),
    path(
        "management/buckets/<int:bucket_id>/",
        BucketAdminDetailView.as_view(),
        name="management_bucket_detail",
    ),
    path(
        "management/buckets/<int:bucket_id>/release/",
        BucketReleaseView.as_view(),
        name="management_bucket_release",
    ),
    path(
        "management/buckets/<int:bucket_id>/recover/",
        BucketRecoverView.as_view(),
        name="management_bucket_recover",
    ),
    path(
        "management/buckets/<int:bucket_id>/delete/",
        BucketDeleteView.as_view(),
        name="management_bucket_delete",
    ),
    path(
        "management/buckets/<int:bucket_id>/retry-delete/",
        BucketRetryDeleteView.as_view(),
        name="management_bucket_retry_delete",
    ),
    path(
        "management/buckets/<int:bucket_id>/configuration/",
        BucketConfigurationView.as_view(),
        name="management_bucket_configuration",
    ),
    path(
        "management/buckets/<int:bucket_id>/configuration/retry/",
        BucketConfigurationRetryView.as_view(),
        name="management_bucket_configuration_retry",
    ),
    path(
        "management/buckets/<int:bucket_id>/uncertainty/observe/",
        BucketActionUncertaintyObserveView.as_view(),
        name="management_bucket_uncertainty_observe",
    ),
    path(
        "management/buckets/<int:bucket_id>/uncertainty/acknowledge/",
        BucketActionUncertaintyAcknowledgeView.as_view(),
        name="management_bucket_uncertainty_acknowledge",
    ),
    path(
        "management/buckets/<int:bucket_id>/configuration/uncertainty/observe/",
        BucketConfigurationUncertaintyObserveView.as_view(),
        name="management_bucket_configuration_uncertainty_observe",
    ),
    path(
        "management/buckets/<int:bucket_id>/configuration/uncertainty/acknowledge/",
        BucketConfigurationUncertaintyAcknowledgeView.as_view(),
        name="management_bucket_configuration_uncertainty_acknowledge",
    ),
    path(
        "management/access-keys/",
        AccessKeyAdminListView.as_view(),
        name="management_access_keys",
    ),
    path(
        "management/access-keys/<int:key_id>/",
        AccessKeyAdminDetailView.as_view(),
        name="management_access_key_detail",
    ),
    path(
        "management/access-keys/<int:key_id>/disable/",
        AccessKeyDisableView.as_view(),
        name="management_access_key_disable",
    ),
    path(
        "management/access-keys/<int:key_id>/enable/",
        AccessKeyEnableView.as_view(),
        name="management_access_key_enable",
    ),
    path(
        "management/access-keys/<int:key_id>/rotate/",
        AccessKeyRotateView.as_view(),
        name="management_access_key_rotate",
    ),
    path(
        "management/access-keys/<int:key_id>/revoke/",
        AccessKeyRevokeView.as_view(),
        name="management_access_key_revoke",
    ),
    path(
        "management/access-keys/<int:key_id>/reveal/",
        AccessKeyRevealView.as_view(),
        name="management_access_key_reveal",
    ),
    path(
        "management/applications/",
        ApplicationBatchAdminListView.as_view(),
        name="management_applications",
    ),
    path(
        "management/applications/<int:application_id>/",
        ApplicationBatchAdminDetailView.as_view(),
        name="management_application_detail",
    ),
    path(
        "management/applications/<int:application_id>/retry/",
        ApplicationBatchRetryView.as_view(),
        name="management_application_retry",
    ),
    path(
        "management/audit-events/",
        AuditEventAdminListView.as_view(),
        name="management_audit_events",
    ),
    path(
        "management/audit-events/<int:event_id>/",
        AuditEventAdminDetailView.as_view(),
        name="management_audit_event_detail",
    ),
    path(
        "management/idempotency-records/",
        IdempotencyRecordAdminListView.as_view(),
        name="management_idempotency_records",
    ),
    path(
        "management/idempotency-records/<int:record_id>/",
        IdempotencyRecordAdminDetailView.as_view(),
        name="management_idempotency_record_detail",
    ),
    path(
        "management/idempotency-records/<int:record_id>/resolve/",
        IdempotencyRecordAdminResolveView.as_view(),
        name="management_idempotency_record_resolve",
    ),
    path(
        "management/users/<int:user_id>/suspend/",
        UserResourceSuspendView.as_view(),
        name="management_user_suspend",
    ),
    path(
        "management/users/<int:user_id>/reactivate/",
        UserResourceReactivateView.as_view(),
        name="management_user_reactivate",
    ),
]
