from django.urls import path

from object_storage.views import ObjectStorageOverviewView
from object_storage.views_auth import (
    FeishuCallbackView,
    FeishuLoginStartView,
    HandoffExchangeView,
)
from object_storage.views_admin import (
    FeishuAppConfigView,
    FeishuAppValidationView,
    StorageResourcePoolDetailView,
    StorageResourcePoolListCreateView,
    StorageResourcePoolValidationView,
    StorageTenantDetailView,
    StorageTenantListCreateView,
)
from object_storage.views_employee import (
    EmployeeApplicationCreateView,
    EmployeeBucketListView,
    EmployeeBucketReleaseView,
    EmployeeCredentialDeliveryView,
    EmployeeCredentialDetailView,
    EmployeeDeliveryTokenView,
    EmployeeRotationPreviewView,
    ManagementAccessKeyRevealView,
    ManagementMembershipReactivateView,
    ManagementMembershipSuspendView,
)

app_name = "object_storage"

urlpatterns = [
    path("overview/", ObjectStorageOverviewView.as_view(), name="overview"),
    path(
        "auth/feishu/start/",
        FeishuLoginStartView.as_view(),
        name="feishu_login_start",
    ),
    path(
        "auth/feishu/callback/",
        FeishuCallbackView.as_view(),
        name="feishu_callback",
    ),
    path(
        "auth/handoff/exchange/",
        HandoffExchangeView.as_view(),
        name="handoff_exchange",
    ),
    path(
        "management/tenants/",
        StorageTenantListCreateView.as_view(),
        name="management_tenants",
    ),
    path(
        "management/tenants/<int:tenant_id>/",
        StorageTenantDetailView.as_view(),
        name="management_tenant_detail",
    ),
    path(
        "management/tenants/<int:tenant_id>/feishu/",
        FeishuAppConfigView.as_view(),
        name="management_feishu_config",
    ),
    path(
        "management/tenants/<int:tenant_id>/feishu/validate/",
        FeishuAppValidationView.as_view(),
        name="management_feishu_validate",
    ),
    path(
        "management/tenants/<int:tenant_id>/resource-pools/",
        StorageResourcePoolListCreateView.as_view(),
        name="management_resource_pools",
    ),
    path(
        "management/resource-pools/<int:pool_id>/",
        StorageResourcePoolDetailView.as_view(),
        name="management_resource_pool_detail",
    ),
    path(
        "management/resource-pools/<int:pool_id>/validate/",
        StorageResourcePoolValidationView.as_view(),
        name="management_resource_pool_validate",
    ),
    path(
        "management/access-keys/<int:key_id>/reveal/",
        ManagementAccessKeyRevealView.as_view(),
        name="management_access_key_reveal",
    ),
    path(
        "management/members/<int:membership_id>/suspend/",
        ManagementMembershipSuspendView.as_view(),
        name="management_member_suspend",
    ),
    path(
        "management/members/<int:membership_id>/reactivate/",
        ManagementMembershipReactivateView.as_view(),
        name="management_member_reactivate",
    ),
    path(
        "workspace/buckets/",
        EmployeeBucketListView.as_view(),
        name="workspace_buckets",
    ),
    path(
        "workspace/buckets/<int:bucket_id>/release/",
        EmployeeBucketReleaseView.as_view(),
        name="workspace_bucket_release",
    ),
    path(
        "workspace/applications/",
        EmployeeApplicationCreateView.as_view(),
        name="workspace_applications",
    ),
    path(
        "workspace/applications/<int:application_id>/delivery-token/",
        EmployeeDeliveryTokenView.as_view(),
        name="workspace_application_delivery_token",
    ),
    path(
        "workspace/credentials/deliver/",
        EmployeeCredentialDeliveryView.as_view(),
        name="workspace_credential_delivery",
    ),
    path(
        "workspace/credentials/rotation-preview/",
        EmployeeRotationPreviewView.as_view(),
        name="workspace_credential_rotation_preview",
    ),
    path(
        "workspace/credentials/<int:key_id>/",
        EmployeeCredentialDetailView.as_view(),
        name="workspace_credential_detail",
    ),
]
