# Generated by Django 5.1.4 on 2026-05-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('url', models.URLField(verbose_name='GitLab URL')),
                ('private_token', models.CharField(max_length=512, verbose_name='Private Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'GitLab 实例',
                'verbose_name_plural': 'GitLab 实例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.IntegerField(verbose_name='GitLab Group ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('path', models.CharField(max_length=512, verbose_name='路径')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='采集时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_groups', to='gitlab_resource.gitlabinstance', verbose_name='GitLab 实例')),
            ],
            options={
                'verbose_name': '注册的群组',
                'verbose_name_plural': '注册的群组',
                'ordering': ['name'],
                'unique_together': {('instance', 'gitlab_id')},
            },
        ),
        migrations.CreateModel(
            name='RegisteredProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.IntegerField(verbose_name='GitLab Project ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('path', models.CharField(max_length=512, verbose_name='路径')),
                ('default_branch', models.CharField(blank=True, max_length=255, verbose_name='默认分支')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='采集时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_projects', to='gitlab_resource.registeredgroup', verbose_name='所属群组')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_projects', to='gitlab_resource.gitlabinstance', verbose_name='GitLab 实例')),
            ],
            options={
                'verbose_name': '注册的项目',
                'verbose_name_plural': '注册的项目',
                'ordering': ['name'],
                'unique_together': {('instance', 'gitlab_id')},
            },
        ),
        migrations.CreateModel(
            name='GitLabWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.IntegerField(blank=True, null=True, verbose_name='GitLab Webhook ID')),
                ('url', models.URLField(verbose_name='Webhook URL')),
                ('push_events', models.BooleanField(default=True, verbose_name='Push 事件')),
                ('tag_push_events', models.BooleanField(default=False, verbose_name='Tag 推送事件')),
                ('merge_requests_events', models.BooleanField(default=False, verbose_name='合并请求事件')),
                ('enable_ssl_verification', models.BooleanField(default=True, verbose_name='启用 SSL 验证')),
                ('collected_at', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='gitlab_resource.registeredproject', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'GitLab Webhook',
                'verbose_name_plural': 'GitLab Webhook',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='GitLabTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tag 名称')),
                ('commit_sha', models.CharField(blank=True, max_length=64, verbose_name='Commit SHA')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='发布日期')),
                ('collected_at', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='gitlab_resource.registeredproject', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'GitLab Tag',
                'verbose_name_plural': 'GitLab Tag',
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GitLabBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='分支名称')),
                ('protected', models.BooleanField(default=False, verbose_name='是否保护')),
                ('last_commit_date', models.DateTimeField(blank=True, null=True, verbose_name='最后提交时间')),
                ('last_commit_sha', models.CharField(blank=True, max_length=64, verbose_name='最后提交 SHA')),
                ('collected_at', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='gitlab_resource.registeredproject', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'GitLab 分支',
                'verbose_name_plural': 'GitLab 分支',
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
