# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitlab_resource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitLabProjectLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="标签名称")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                        verbose_name="标签标识",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "GitLab 项目标签",
                "verbose_name_plural": "GitLab 项目标签",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="registeredproject",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="gitlab_resource.gitlabprojectlabel",
                verbose_name="资源标签",
            ),
        ),
    ]
