# Generated by Codex on 2026-06-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gitlab_resource", "0002_gitlabprojectlabel_registeredproject_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitLabCollectionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("project_path", models.CharField(max_length=512, verbose_name="项目路径")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=24,
                        verbose_name="状态",
                    ),
                ),
                ("branches_count", models.PositiveIntegerField(default=0, verbose_name="分支数量")),
                ("tags_count", models.PositiveIntegerField(default=0, verbose_name="标签数量")),
                ("webhooks_count", models.PositiveIntegerField(default=0, verbose_name="Webhook 数量")),
                ("message", models.CharField(blank=True, max_length=255, verbose_name="消息")),
                ("error", models.TextField(blank=True, verbose_name="错误信息")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_records",
                        to="gitlab_resource.registeredproject",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitLab 采集记录",
                "verbose_name_plural": "GitLab 采集记录",
                "ordering": ["-started_at"],
            },
        ),
    ]
