# Generated by Codex on 2026-06-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gitlab_resource", "0003_gitlabcollectionrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GitLabOperationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("collect_projects", "采集项目"),
                            ("collect_resources", "采集项目资源"),
                            ("branch_create", "新增分支"),
                            ("branch_delete", "删除分支"),
                            ("branch_protect", "保护分支"),
                            ("branch_unprotect", "取消保护分支"),
                            ("tag_create", "新增标签"),
                            ("tag_delete", "删除标签"),
                            ("webhook_create", "新增 Webhook"),
                            ("webhook_update", "编辑 Webhook"),
                            ("webhook_delete", "删除 Webhook"),
                            ("project_label_update", "项目标签变更"),
                            ("project_label_delete", "删除资源标签"),
                        ],
                        max_length=64,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("partial_success", "部分成功"), ("failed", "失败")],
                        default="success",
                        max_length=24,
                        verbose_name="状态",
                    ),
                ),
                ("target_summary", models.CharField(blank=True, max_length=512, verbose_name="目标摘要")),
                ("request_data", models.JSONField(blank=True, default=dict, verbose_name="请求参数")),
                ("result_data", models.JSONField(blank=True, default=dict, verbose_name="执行结果")),
                ("total_count", models.PositiveIntegerField(default=0, verbose_name="总数")),
                ("success_count", models.PositiveIntegerField(default=0, verbose_name="成功数")),
                ("failed_count", models.PositiveIntegerField(default=0, verbose_name="失败数")),
                ("error", models.TextField(blank=True, verbose_name="错误信息")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gitlab_operation_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_records",
                        to="gitlab_resource.registeredgroup",
                        verbose_name="群组",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_records",
                        to="gitlab_resource.gitlabinstance",
                        verbose_name="GitLab 实例",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_records",
                        to="gitlab_resource.registeredproject",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitLab 操作记录",
                "verbose_name_plural": "GitLab 操作记录",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="gitlaboperationrecord",
            index=models.Index(fields=["action", "-started_at"], name="gitlab_reso_action_d7249e_idx"),
        ),
        migrations.AddIndex(
            model_name="gitlaboperationrecord",
            index=models.Index(fields=["status", "-started_at"], name="gitlab_reso_status_8eb7fb_idx"),
        ),
    ]
