# Generated by Django 5.1.4 on 2026-08-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_resource', '0004_gitlaboperationrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gitlaboperationrecord',
            new_name='gitlab_reso_action_3f4a09_idx',
            old_name='gitlab_reso_action_d7249e_idx',
        ),
        migrations.RenameIndex(
            model_name='gitlaboperationrecord',
            new_name='gitlab_reso_status_3c0431_idx',
            old_name='gitlab_reso_status_8eb7fb_idx',
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='confidential_issues_events',
            field=models.BooleanField(default=False, verbose_name='保密 Issue 事件'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='confidential_note_events',
            field=models.BooleanField(default=False, verbose_name='保密备注事件'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='GitLab 创建时间'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='deployment_events',
            field=models.BooleanField(default=False, verbose_name='部署事件'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='feature_flag_events',
            field=models.BooleanField(default=False, verbose_name='Feature Flag 事件'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='issues_events',
            field=models.BooleanField(default=False, verbose_name='Issue 事件'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='job_events',
            field=models.BooleanField(default=False, verbose_name='Job 事件'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='note_events',
            field=models.BooleanField(default=False, verbose_name='备注事件'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='pipeline_events',
            field=models.BooleanField(default=False, verbose_name='Pipeline 事件'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='push_events_branch_filter',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Push 事件分支过滤'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='releases_events',
            field=models.BooleanField(default=False, verbose_name='Release 事件'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='repository_update_events',
            field=models.BooleanField(default=False, verbose_name='仓库更新事件'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='resource_access_token_events',
            field=models.BooleanField(default=False, verbose_name='资源访问令牌事件'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Secret Token'),
        ),
        migrations.AddField(
            model_name='gitlabwebhook',
            name='wiki_page_events',
            field=models.BooleanField(default=False, verbose_name='Wiki 页面事件'),
        ),
    ]
